### ISSUE TITLE
Equipment Needed Breakfast

### ISSUE THREAD

**Issue by surbhigarg30** [IntroToCode/CodeMates4_Fall22#11]
## 💬 Discussion topic

Need to mention all the equipment needed for the breakfast receipe

## ❗ Potential issues

My not be able to make the recipe without sufficient equipment

## 👥 People to consult

@andrewfeeney13 

## 📃 Details

Note all of the equipment needed for the breakfast receipe

**Comment by andrewfeeney13** [comment]
Hey @surbhigarg30! I created a pull request for this that is pending approval. Once approved, we can close this :)
