### ISSUE TITLE
Create notes for breakfast recipe

### ISSUE THREAD

**Issue by surbhigarg30** [IntroToCode/CodeMates4_Fall22#13]
## 💬 Discussion topic

Add any notes needed for the breakfast recipe

## ❗ Potential issues

Not mentioning specific details could result in the recipe not turning out as great as we would want

## 👥 People to consult

@aaronveeraberkeley 

## 📃 Details

Add any relevant notes needed for the breakfast recipe

**Comment by surbhigarg30** [comment]
pull request done

**Comment by andrewfeeney13** [comment]
added pull request #28 which will close out this issue once merged. Pending approval ☘️ 🤞
