### ISSUE TITLE
Add steps for preparation for dinner recipe

### ISSUE THREAD

**Issue by surbhigarg30** [IntroToCode/CodeMates4_Fall22#14]
## 💬 Discussion topic

Add steps for preparation for dinner recipe

## ❗ Potential issues

Not following the steps could ruin the dish

## 👥 People to consult

@aaronveeraberkeley 

## 📃 Details

Add all steps for the preparation of the dinner recipe

**Comment by aaronveeraberkeley** [comment]
Created request #34  - to close out, please approve this! @surbhigarg30
