### ISSUE TITLE
Add notes to dinner

### ISSUE THREAD

**Issue by jsham042** [IntroToCode/CodeMates4_Fall22#24]
## 💬 Discussion topic

Discuss the name to make sure we like it.

## ❗ Potential issues

We could use the additional toppings as shown on the recipe online, or suggest our own.

## 👥 People to consult
@aayushmisra-bot @andrewfeeney13 

## 📃 Details

Tie back to pull request

**Comment by andrewfeeney13** [comment]
added pull request #22 for dinner notes to issue
