### ISSUE TITLE
Add steps for preparation to Breakfast

### ISSUE THREAD

**Issue by jsham042** [IntroToCode/CodeMates4_Fall22#7]
## 💬 Discussion topic

What steps are there to prepare the breakfast?

## ❗ Potential issues

We need to make sure we have the right steps for each ingredient.

## 👥 People to consult

@andrewfeeney13 @aayushmisra-bot @surbhigarg30 

## 📃 Details

Add preparation steps to 'breakfast'. To be completed by @aaronveeraberkeley

**Comment by surbhigarg30** [comment]
This is done and approved!
